### ISSUE TITLE
deploy wasm contract on substrate

### ISSUE THREAD

**Issue by Lbqds** [pepyakin/substrate-contracts-adder#1]
Thanks for your example about how to write substrate wasm contract, but I have some questions:

1. there are a lot of external functions in `src/ext.rs`, is there any lib like [pwasm-ethereum](https://github.com/paritytech/pwasm-ethereum/blob/master/src/ext.rs) do these things? 

2. Is there any tutorial about how to write substrate contract with javascript or other programming language?

Thanks

**Comment by pepyakin** [comment]
Sorry for missing this! My answer for both question is: not yet! This is because it's a little bit early for creating a large ecosystem since the foundation is still a bit in a flux for it.

However, I'd say it is ripe enough for starting experimentation!
